### ISSUE TITLE
Use Makie for 3D barplot

### ISSUE THREAD

**Issue by Moelf** [gojakuch/JetReconstruction.jl#3]
here's a dummy example:
<details>

```julia
using WGLMakie
begin
	N = 100
	δ = 0.02
	cs = repeat(1:5, N÷5)
	heights = rand(N) * 200
	meshscatter(
                                # this is needed because Makie would flatten to 2D if all Zs are the same
		Point3f.(rand(N), rand(N), 0.00001rand(N)); 
	  	color = cs, 
		markersize = Vec3f.(δ, δ, heights),
		colormap = :Spectral_7,
		marker = Rect3f(Vec3f(0), Vec3f(1)),
	 	axis = (type = Axis3, perspectiveness = 0.5, azimuth = 2.4,
            xlabel = "ϕ", ylabel = "η", zlabel = "kt",
		    limits = (nothing, nothing, nothing, nothing, 0, 200)
		),
	    shading=false
	)
end
```
</details>

![image](https://user-images.githubusercontent.com/5306213/180926550-519ad26f-3517-4fe3-8d9f-7bb132ff6906.png)

It should also work with GLMakie.jl, but 3D might be a bit broken with CairoMakie...

**Comment by Moelf** [comment]
`		    limits = (nothing, nothing, nothing, nothing, 0, 200)` this line exists because:

- https://github.com/JuliaPlots/Makie.jl/issues/2182

**Comment by Moelf** [comment]
ok, actually doesn't look that shit when using `svg`:
```julia
using CairoMakie
CairoMakie.activate!(type = "SVG")
begin
	N = 100
	δ = 0.01
	cs = repeat(1:5, N÷5)
	heights = rand(N) * 200
	meshscatter(
		Point3f.(rand(N), rand(N), 0.00001rand(N)); 
	  	color = cs,
		markersize = Vec3f.(δ, δ, heights),
		colormap = :Spectral_7,
		marker = Rect3f(Vec3f(0), Vec3f(1)),
	 	figure = (resolution=(700,600),),
		axis = (
			type = Axis3, perspectiveness = 0.5, azimuth = 2.6, elevation=0.5,
                        xlabel = "ϕ", ylabel = "η", zlabel = "kt",
		        limits = (nothing, nothing, nothing, nothing, 0, 200)
		),
	    shading=false
	)
end
```
![image](https://user-images.githubusercontent.com/5306213/180928310-b4fb8be9-02c9-4c0a-882b-c7dab37a9952.png)

**Comment by gojakuch** [comment]
This is awesome, mate! This looks like exactly what we need. Would you like to make a pull request or should I just use your code?

**Comment by Moelf** [comment]
Just go ahead to use it for now to clean up the dependency, we can worry about usability and beautifying it later
