### ISSUE TITLE
Loop optimisation

### ISSUE THREAD

**Issue by gojakuch** [gojakuch/JetReconstruction.jl#6]
I've been trying to optimise the code for sequential recombination algorithm in Julia and spotted an interesting fact. 

Below you can see a very simple piece of code that is basically a translation of the C++ FastJet code. The profiler shows that lines that only have `nndist = Δ2` in them take up as much time as really computationally heavy lines like `Δ2 = _dist(i, j, _eta, _phi)`. I checked the stack that the profiler throws out and it's actually calling the == operation inside of the iterate() function that causes that. So this probably comes not from the assignment itself but from the end of the loop iteration. Simple loops typically get optimised but here it's something strange.

I used Profile.jl and profiled the entire algorithm in a loop. This function is called from there frequently and only exists to be compiled to avoid dynamic dispatch in the main algorithm.

```julia
# src/Algo.jl @ line 45
function _upd_nn_nocross!(i::Int, from::Int, to::Int, _eta, _phi, _R2, _nndist, _nn)
    nndist::Float64 = _R2
    nn = i
    Δ2::Float64 = 0.0
    for j in from:(i-1)
        Δ2 = _dist(i, j, _eta, _phi)
        if Δ2 <= nndist
            nn = j
            nndist = Δ2 # too long for an assignment
        end
    end
    for j in (i+1):to
        Δ2 = _dist(i, j, _eta, _phi)
        if Δ2 <= nndist
            nn = j
            nndist = Δ2 # too long for an assignment
        end
    end
    _nndist[i] = nndist
    _nn[i] = nn
    nothing
end
```

**Comment by Moelf** [comment]
can you confirm this is a representative workload?
```julia
julia> const input2 = loadjets("./test/data/11.dat");

julia> f() = for _=1:10 anti_kt(input2, R=0.7) end;

julia> @time f()
  0.549266 seconds (72.79 k allocations: 8.631 MiB)

julia> @benchmark f()
BenchmarkTools.Trial: 10 samples with 1 evaluation.
 Range (min … max):  544.617 ms … 554.028 ms  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     546.893 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):   548.198 ms ±   3.530 ms  ┊ GC (mean ± σ):  0.04% ± 0.12%

  █   ▁      ▁ ▁ ▁       ▁                      ▁       ▁     ▁  
  █▁▁▁█▁▁▁▁▁▁█▁█▁█▁▁▁▁▁▁▁█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█▁▁▁▁▁▁▁█▁▁▁▁▁█ ▁
  545 ms           Histogram: frequency by time          554 ms <

 Memory estimate: 8.63 MiB, allocs estimate: 72790.

julia> @profview f()
```

**Comment by gojakuch** [comment]
Yes, should be.

**Comment by tamasgal** [comment]
I am confused: `nndist = Δ2 # too long for an assignment` is taking so long? `Δ2` is coming from `dist()`, is that guaranteed to be a `Float64` (which `nndist` is)?
